version: '3.8'
services:
  whisper-app:
    build: .
    ports:
      - "8501:8501"  # Streamlit
    volumes:
      - ./backend:/app
    env_file:
      - .env
    # devices:
    #   - "/dev/snd:/dev/snd"  # オーディオデバイスへのアクセス